import turtle
bob=turtle.Turtle()
##Square and Triangle
bob.pencolor('Blue')
bob.pensize(10)
bob.forward(100)
bob.left(90)
bob.pencolor('Purple')
bob.pensize(30)
bob.forward(100)
bob.left(90)
bob.pencolor('Red')
bob.pensize(50)
bob.forward(100)
bob.left(90)
bob.pencolor('Black')
bob.pensize(70)
bob.forward(100)
bob.left(90)
bob.penup()
bob.forward(150)
bob.pendown()
bob.left(60)
bob.pencolor('Orange')
bob.pensize(20)
bob.forward(100)
bob.right(120)
bob.pencolor('Green')
bob.pensize(40)
bob.forward(100)
bob.right(120)
bob.pencolor('Yellow')
bob.pensize(60)
bob.forward(100)
bob.right(120)

##Dotted line
##bob.penup()
##bob.backward(300)
##bob.pendown()
##bob.forward(50)
##bob.penup()
##bob.forward(50)
##bob.pendown()
##bob.forward(50)
##bob.penup()
##bob.forward(50)
##bob.pendown()
##bob.forward(50)
##bob.penup()
##bob.forward(50)
##bob.pendown()
##bob.forward(50)
##bob.penup()
##bob.forward(50)
##bob.pendown()
##bob.forward(50)
##bob.penup()
##bob.forward(50)
##bob.pendown()
##bob.forward(50)
##bob.penup()
##bob.forward(50)
##bob.pendown()


