import turtle
##t = turtle.Turtle()
##t.pensize(4)
##t.color("yellow")
##t.pencolor("black")
##t.begin_fill() 
##t.circle(100)
##t.end_fill()
##t.color("black")
##t.penup()
##t.goto(-50,80)
##t.begin_fill()
##t.circle(20)
##t.end_fill()
##t.goto(50,80)
##t.begin_fill()
##t.circle(20)
##t.end_fill()
##t.goto(0,40)
##t.color("pink")
##t.begin_fill()
##t.circle(10)
##t.end_fill()
##t.goto(0,150)
##t.color('purple')
##t.begin_fill()
##t.forward(100)
##t.left(90)
##t.forward(100)
##t.left(90)
##t.forward(200)
##t.left(90)
##t.forward(100)
##t.left(90)
##t.forward(100)
##t.left(90)
##t.end_fill()
##t.goto(0,250)
##t.right(90)
##t.color('red')
##t.begin_fill()
##t.forward(50)
##t.left(90)
##t.forward(50)
##t.left(90)
##t.forward(50)
##t.end_fill()
##t.color('blue')
##t.begin_fill()
##t.forward(50)
##t.left(90)
##t.forward(50)
##t.left(90)
##t.forward(50)
##t.end_fill()

##tina = turtle.Turtle()
##tina.color("green") # tina is a green turtle
##jamie = turtle.Turtle()
##jamie.color("blue") # jamie is a blue turtle
##omar = turtle.Turtle()
##omar.color("red") # omar is a red turtle
##tina.forward(300) # tina will move first
##jamie.forward(200) # then jamie will move
##omar.forward(100)


q = turtle.Turtle()
w = turtle.Turtle()
e = turtle.Turtle()
r = turtle.Turtle()
t = turtle.Turtle()
y = turtle.Turtle()
##q.speed(0)
##w.speed(0)
##e.speed(0)
##r.speed(0)
##t.speed(0)
##y.speed(0)
q.shape('turtle')
w.shape('turtle')
e.shape('turtle')
r.shape('turtle')
t.shape('turtle')
y.shape('turtle')
q.color('red')
w.color('orange')
e.color('yellow')
r.color('green')
t.color('blue')
y.color('purple')
q.penup()
q.forward(30)
q.hideturtle()
w.penup()
w.forward(30)
w.hideturtle()
e.penup()
e.forward(30)
e.hideturtle()
r.penup()
r.forward(30)
r.hideturtle()
t.penup()
t.forward(30)
t.hideturtle()
y.penup()
y.forward(30)
