import turtle
bob = turtle.Turtle()
import turtle
tod = turtle.Turtle()
bob.pencolor('blue')
tod.pencolor('red')
bob.penup()
tod.penup()
bob.goto(0,100)
tod.goto(0,-100)
bob.pendown()
bob.circle(50)
tod.write('1 done. 4 to go!')
tod.right(90)
tod.forward(10)
bob.right(72)
bob.circle(50)
tod.write('2 done. 3 to go!')
tod.forward(10)
bob.right(72)
bob.circle(50)
tod.write('3 done. 2 to go!')
tod.forward(10)
bob.right(72)
bob.circle(50)
tod.write('4 done. 1 to go!')
tod.forward(10)
bob.right(72)
bob.circle(50)
tod.write('5 done. 0 to go!')
tod.forward(10)
tod.write('good job, bob!')
